# Generated by Django 4.2 on 2023-04-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marvel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movies_img', models.ImageField(upload_to='movies_img')),
                ('movies', models.FileField(upload_to='movies')),
            ],
        ),
    ]
