# Generated by Django 4.2 on 2023-04-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
