# Generated by Django 4.2 on 2023-04-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0003_disney_ng_pixer_star_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Disney',
        ),
        migrations.DeleteModel(
            name='Ng',
        ),
        migrations.DeleteModel(
            name='Pixer',
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
