# Generated by Django 4.2 on 2023-04-16 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('des', '0004_category_delete_disney_delete_ng_delete_pixer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cg', to='des.category'),
        ),
    ]
